### ISSUE TITLE
Lobby/시간표 표시 구현

### ISSUE THREAD

**Issue by MadeByZiNo** [Goranies/ProjectRepository#20]
1. 요일의 1시간마다 각자 id를가진 textView존재
 (월 9~10 , 화 14~15)등등

2. 시간표 데이터베이스 기준으로 시간범위에 해당하는만큼의 textView의 backgroundColor 색칠

3. Text는 데이터베이스의 강의명으로 바꾸기

4. 불러오기기능을 사용해 다른 시간표를 기준으로 다시 색칠 및 text바꾸기

(TextView말고  클릭하고 삭제하거나 하는 기능을 위해 내일 다시 button으로 바꿀예정)

더 좋은 방법이나 아이디어
몇분간격으로도 색을 칠할수있는 아이디어 알려주세요
위의대로라면 구현은 되겠는데 첫발 잘못딛으면 고치기 빡세서

**Comment by byungmeo** [comment]
에타 참조함
![image](https://user-images.githubusercontent.com/37506142/128175613-280f0aa9-02d0-40d2-b89a-036ae20d9fbe.png)

우선 동그라미친 강의시간 영역은 하나의 버튼인 것으로 확인됨.
강의 시간에 따라서 버튼의 layout_height 속성을 동적으로 지정해야 할 것 같음

시간표table은 그대로 두되 시각적인 역할과 가이드 역할만 하면 될 것 같음
예로들어 각 강의시간버튼의 layout_width 속성은 반드시 해당 시간표table 요일 열의 width와 동일하게..

해상도 이슈를 어떻게 해결할 것인지가 가장 중요해 보임
해상도가 어떻게 되든 비율은 항상 같으니,
시간표table 각각의 칸의 width와 height 속성을 이용하면 해상도 이슈 없이 동적으로 크기가 정해질 수 있을 것 같음
